# fly.toml app configuration file generated for samezu-bot on 2025-08-05T03:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "samezu-bot"
primary_region = "nrt"  # Tokyo region

[build]

# This is a background worker, not a web service
[processes]
  app = "python run_bot.py"

[env]
  PORT = "8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 